# Generated by Django 5.0.4 on 2024-05-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('tan', 'Tan'), ('orange', 'Orange'), ('cream', 'Cream'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('fawn', 'fawn'), ('purple', 'Purple'), ('pink', 'Pink'), ('multi', 'Multi-color'), ('other', 'Other')], default='black', max_length=50),
        ),
    ]
