# Generated by Django 5.0.4 on 2024-05-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_pet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='custom_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('tan', 'Tan'), ('orange', 'Orange'), ('cream', 'Cream'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue'), ('fawn', 'fawn'), ('purple', 'Purple'), ('pink', 'Pink'), ('other', 'Other')], max_length=50),
        ),
    ]
