# Generated by Django 5.0.4 on 2024-05-06 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_medicalrecord_uploaded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vaccinationrecord',
            name='vaccine_type',
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='document',
            field=models.FileField(blank=True, upload_to='vaccination_records/'),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
